### ISSUE TITLE
Get no Values

### ISSUE THREAD

**Issue by 53845714nF** [trvrnrth/esphome-bsec-bme680#15]
Hello, 
I have an ESP 8266 (m1n1 Board).

I use this configuration:
```
esphome:
  name: bme680
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "****"
  password: "****"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Bme680 Fallback Hotspot"
    password: "w1bhFGorvUp6"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "****t"

ota:
  password: "*****"

# 
i2c:
  sda: 4
  scl: 5
  scan: True
  id: bus_a

bme680_bsec:
    # i2c address override (default is 0x76)
    address: 0x77

    # Temperature offset if device is in enclosure and reads too high (default is 0)
    temperature_offset: 0.9

    # Mode for IAQ sensors if device is mobile (default is static)
    iaq_mode: mobile

    # Interval at which to save BSEC state (default is 6 hours)
    state_save_interval: 4h

sensor:
  - platform: bme680_bsec
    temperature:
      name: "BME680 Temperature"
    pressure:
      name: "BME680 Pressure"
    humidity:
      name: "BME680 Humidity"
    gas_resistance:
      name: "BME680 Gas Resistance"
    iaq:
      name: "BME680 IAQ"
    co2_equivalent:
      name: "BME680 CO2 Equivalent"
    breath_voc_equivalent:
      name: "BME680 Breath VOC Equivalent"

text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "BME680 IAQ Accuracy"
```
But i get this Message:
`[17:51:20][E][bme680_bsec.sensor:056]: Communication failed with BSEC Status: 0, BME680 Status: -2`

As an result, I don't get any Value from the sensor. Do you have any ideas what I did wrong?
