### ISSUE TITLE
including the bsec lib

### ISSUE THREAD

**Issue by FlorianLudwig** [trvrnrth/esphome-bsec-bme680#17]
Hi,

how do I include the bsec lib into the esphome build process?

I am getting the following error:

```
In file included from src/esphome/components/bme680_bsec/bme680_bsec.cpp:3:0:
src/esphome/components/bme680_bsec/bme680_bsec.h:10:18: fatal error: bsec.h: No such file or directory
```

Thanks :)

**Comment by FlorianLudwig** [comment]
Solution:

```
esphome:
  platformio_options:
    lib_deps:
     - "boschsensortec/BSEC-Arduino-library"
 ```

The important part is to not add a `@ version` at the end. Otherwise it fails.
