### ISSUE TITLE
support [id] value for ifclause

### ISSUE THREAD

**Issue by itsyoshio** [trvrnrth/esphome-bsec-bme680#22]
I'd be nice if the Library could support [id] to be able to do things like conditionals on the text_sensor's state.

```yaml
text_sensor:
  - platform: bme680_bsec
    id: iaq_accuracy
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      name: "BME680 IAQ Accuracy"
    on_value:
      then:
        - if:
          condition:
            or: 
              - text_sensor.state:
                id: iaq_accuracy
                state: 'Uncertain'
```

Since `id: iaq_accuracy` is not a valid Line, text_sensor.state->id does not work

ESPHome Docs for this feature are found [here](https://esphome.io/components/text_sensor/index.html)

**Comment by trvrnrth** [comment]
You're putting the id in the wrong place. The following ought to work:
```yaml
text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      # IAQ accuracy as a text value of Stabilizing, Uncertain, Calibrating, Calibrated
      id: iaq_accuracy
      name: "BME680 IAQ Accuracy"
    on_value:
      then:
        - if:
          condition:
            or: 
              - text_sensor.state:
                id: iaq_accuracy
                state: 'Uncertain'
```
